action_id: trunk-upgrade-available
date: 2023-09-07 11:25:39
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1694085939
full_timestamp:
  nanos: 680385000
  seconds: 1694085939
trunk_version: 1.15.0
