action_id: trunk-upgrade-available
date: 2023-09-07 14:23:49
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1694096629
full_timestamp:
  nanos: 18116000
  seconds: 1694096629
trunk_version: 1.15.0
